ktor:
    deployment:
        port: 8000
        host: "192.168.0.101"
    application:
        modules: [ com.encryptor.app.ApplicationKt.module ]

jwt:
    issuer: "http://192.168.0.101:8000"
    domain: "http://192.168.0.101:8000"
    audience: "users"
    realm: "ktor sample app"